import ImageUploadForm from '@/components/ImageUploadForm'
import Head from 'next/head'

export default function Generator() {
  return (
    <div className='flex items-center justify-center min-h-[calc(100vh-100px)]'>
      <Head>
        <title>Truc - Generator</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ImageUploadForm />
    </div>
  )
}
